name: Angular Ci

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install package
        run: npm ci --legacy-peer-deps
      - name: Lint
        run: npm run lint
      - name: Unit Schematics test
        run: npm run test-schematics
      - name: Build
        run: npm run package && npm run build
