name: Node.js Package

on:
  push:
    tags:
      - v*

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - run: npm run lint
      - run: npm run package
      - run: npm run build

  publish-npm:
    needs: tests
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - run: npm run package
      - run: npm run copyfile
      - run: cd dist/ngx-apexcharts && npm publish
  release:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install Conventional Changelog CLI
        run: npm install -g conventional-changelog-cli
      - name: Genterate Changelog
        id: changelog
        run: |
          git fetch origin --prune
          git fetch --tags --force
          LAST_TAG=$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1))
          conventional-changelog -p angular -o --commit-path . --release-count 2 --tag-prefix v | sed '/^# \[0.0.0\]/,+2d' > CHANGELOG.md
          echo "CHANGLOG_CONTENT<<EOF" >> $GITHUB_ENV
          cat CHANGELOG.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        shell: bash
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ${{ env.CHANGLOG_CONTENT }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
