name: Sync Apex Types and Release

on:
  schedule:
    - cron: "0 0 1 * *" # Runs at 00:00 on the first day of every month
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  sync-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout damingerdai/ngx-apexcharts
        uses: actions/checkout@v4
        with:
          repository: "damingerdai/ngx-apexcharts"
          path: "ngx-apexcharts"
          fetch-depth: 0 # Important for version tags
          token: ${{ secrets.SYNC_TOKEN }}

      - name: Checkout apexcharts/ng-apexcharts
        uses: actions/checkout@v4
        with:
          repository: "apexcharts/ng-apexcharts"
          path: "ng-apexcharts"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Sync apex-types.ts
        run: |
          mkdir -p ./ngx-apexcharts/projects/ngx-apexcharts/src/lib/model/
          cp ./ng-apexcharts/projects/ng-apexcharts/src/lib/model/apex-types.ts ./ngx-apexcharts/projects/ngx-apexcharts/src/lib/model/apex-types.ts
          cd ./ngx-apexcharts
          if git diff --exit-code; then
            echo "No changes detected, skipping version bump."
          else
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add projects/ngx-apexcharts/src/lib/model/apex-types.ts
            DATE=$(date +'%Y-%m-%d')
            git commit -m "feat: update apex type from upstream to ${DATE}."
            echo "Changes detected"
            yarn install --frozen-lockfile
            npm run release:patch
            git push --follow-tags origin develop
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_TOKEN }}
